version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: stream_pilot_db
      POSTGRES_USER: stream_pilot_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - stream-pilot-db:/var/lib/postgresql/data

  streampilot.api:
    build:
      context: .
      dockerfile: StreamPilot.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__StreamPilotDatabase=Host=postgres;Port=5432;Database=stream_pilot_db;Username=stream_pilot_user;Password=your_password;
  
  streampilot.admin:
    build:
      context: .
      dockerfile: StreamPilot.Admin/Dockerfile
    ports:
      - "5001:80"

  streampilot.ui:
    build:
      context: .
      dockerfile: StreamPilot.UI/Dockerfile
    ports:
      - "5002:80"

volumes:
  stream-pilot-db: